FROM openjdk:16-alpine3.13

WORKDIR /app

COPY p3SocketsMc ./p3SocketsMc

RUN javac p3SocketsMc/MultiClient.java p3SocketsMc/Servidor.java

EXPOSE 8080 8088 8888

CMD ["java", "p3SocketsMc.Servidor"]
